### ISSUE TITLE
run kiwitcms/kiwi:latest on Kubernetes

### ISSUE THREAD

**Issue by Hezaveh** [kiwitcms/Kiwi#2337]
I am trying to run kiwitcms/kiwi image on Kubernetes. I got the service, pod and deployment run. 

```
kubectl get deployment,svc,pods,ingress -n kiwi -o wide
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                       SELECTOR
deployment.apps/kiwi   1/1     1            1           29m   kiwi         kiwitcms/kiwi:latest         run=kiwi

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE   SELECTOR
service/kiwi         ClusterIP   10.108.84.90   <none>        80/TCP      29m   run=kiwi

NAME                        READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
pod/kiwi-75bbdd79d6-fbgjp   1/1     Running   0          29m   172.17.0.7   minikube   <none>           <none>

NAME                      HOSTS         ADDRESS         PORTS     AGE
ingress.extensions/kiwi   example.com   192.168.39.37   80, 443   6m45s
```

Here is my ingress.yml file. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiwi
  namespace: kiwi
spec:
  tls:
  - secretName: example-com-tls
    hosts:
      - example.com
  rules:
  - host: example.com
    http:
      paths:
      - path: /accounts/login
        backend:
          serviceName: kiwi
          servicePort: 80
```

I get "502 Bad Gateway" error when I send following curl command:

`curl -k http://example.com/accounts/login`

Any idea why this is happening?

I also tried the ingress.yml without tls and got same result.
