### ISSUE TITLE
Feature: KIWI_DB_PASSWORD and Docker Secrets in docker-compose

### ISSUE THREAD

**Issue by vmelnych** [kiwitcms/Kiwi#2606]
**Description**
I want to secure my docker environment by not exposing db user and password in the ENV parameters.
To secure better docker environment, the Docker introduced `Docker Secrets`.
It is described in [Postgres](https://hub.docker.com/_/postgres) and [MySQL](https://hub.docker.com/_/mysql)
Otherwise I can secure the DB container, but the Kiwi container is not yet compatible.

**The solution I'd like**
Introduce a native support to the `_FILE` environment parameters, e.q.
```yml
environment:
    KIWI_DB_HOST: db
    KIWI_DB_PORT: 3306
    KIWI_DB_NAME: kiwi
    KIWI_DB_USER_FILE: /run/secrets/db_user
    KIWI_DB_PASSWORD_FILE: /run/secrets/db_password
secrets:
    - db_user
    - db_password
```

**Alternatives I've considered**
Alternatively the `db_connect` method could first check if the passed env parameter `KIWI_DB_PASSWORD` points to a file, and read it from the file instead of just using the line `/run/secrets/db_password` as the password.
```yml
environment:
    KIWI_DB_PASSWORD: /run/secrets/db_password
secrets:
    - db_password
```

Thanks for your consideration!
